const LOCAL_WP_CONTENT = "/wp-content";

export const LEGACY_SITE_URL =
  process.env.NEXT_PUBLIC_LEGACY_SITE_URL || "https://api.veloriavault.com";

export const OUTBOUND_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36";

export const LEGACY_GLOBAL_STYLES = [
  "https://fonts.googleapis.com/css?family=Playfair+Display%3A400%2C600%2C500%7CInter%3A400%2C600%7CLato%3A400%2C700&display=swap",
  `${LOCAL_WP_CONTENT}/plugins/elementor/assets/css/frontend.min.css`,
  `${LOCAL_WP_CONTENT}/plugins/elementor/assets/css/widget-heading.min.css`,
  `${LOCAL_WP_CONTENT}/plugins/elementor/assets/css/widget-social-icons.min.css`,
  `${LOCAL_WP_CONTENT}/plugins/elementor/assets/css/widget-icon-box.min.css`,
  `${LOCAL_WP_CONTENT}/plugins/elementor/assets/css/widget-image.min.css`,
  `${LOCAL_WP_CONTENT}/plugins/elementor/assets/css/widget-text-editor.min.css`,
  `${LOCAL_WP_CONTENT}/uploads/elementor/css/post-19.css`,
  `${LOCAL_WP_CONTENT}/uploads/elementor/css/post-10.css`,
  `${LOCAL_WP_CONTENT}/uploads/elementor/css/post-2639.css`,
  `${LOCAL_WP_CONTENT}/uploads/elementor/css/post-2723.css`,
  `${LOCAL_WP_CONTENT}/uploads/elementor/css/post-2682.css`,
  `${LOCAL_WP_CONTENT}/uploads/elementor/css/post-4053.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/base.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/helpers-wpb-elem.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/int-elem-base.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/int-elementor-pro.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woocommerce-base.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/mod-star-rating.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-mod-block-notices.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/wp-blocks.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-base.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/mod-tools.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-el-base.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-mod-login-form.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-el-my-account.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-el-cart-side.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-el-cart.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-widget-shopping-cart.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-widget-product-list.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-el-mobile-nav-dropdown.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-el-search.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/el-banner.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/el-banner-hover-zoom.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/el-banner-btn-hover.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/el-button.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/el-tabs.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/el-product-tabs.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/mod-sticky-loader.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-product-loop.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-product-loop-standard.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-mod-add-btn-replace.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-mod-swatches-base.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/lib-swiper.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/woo-mod-product-labels.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/lib-magnific-popup.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/mod-animations-transform.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/mod-transform.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/lib-swiper-arrows.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/lib-swiper-pagin.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/opt-widget-collapse.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/opt-scrolltotop.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/header-el-my-account-sidebar.min.css`,
  `${LOCAL_WP_CONTENT}/themes/woodmart/css/parts/opt-bottom-toolbar.min.css`,
  `${LOCAL_WP_CONTENT}/uploads/2026/03/xts-header_650020-1772433770.css`,
  `${LOCAL_WP_CONTENT}/uploads/2026/02/xts-theme_settings_default-1771221841.css`,
];
